apiVersion: v1
kind: Service
metadata:
  name: svc-argo
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80

---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argo
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: myapp
      template:
        metadata:
          labels:
            app: myapp
        spec:
          containers:
          - name: myargo
            image: wonjune95/keduitargo:0913
            ports:
            - containerPort: 80