    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: web-dp
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: myapp
      template:
        metadata:
          labels:
            app: myapp
        spec:
          containers:
          - name: web-ctn
            image: ilovesnows/test:first
            ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-lb
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
    type: LoadBlancer
